//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrera
    {
        public carrera()
        {
            this.alumno = new HashSet<alumno>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string NombreCorto { get; set; }
    
        public virtual ICollection<alumno> alumno { get; set; }
    }
}
