//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class docente
    {
        public docente()
        {
            this.prestamo = new HashSet<prestamo>();
        }
    
        public int NumeroEmpleado { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
    
        public virtual ICollection<prestamo> prestamo { get; set; }
    }
}
