//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class estadomaterial
    {
        public estadomaterial()
        {
            this.prestamomaterial = new HashSet<prestamomaterial>();
            this.prestamomaterial1 = new HashSet<prestamomaterial>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<prestamomaterial> prestamomaterial { get; set; }
        public virtual ICollection<prestamomaterial> prestamomaterial1 { get; set; }
    }
}
