//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class laboratorioEntities : DbContext
    {
        public laboratorioEntities()
            : base("name=laboratorioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<carrera> carrera { get; set; }
        public DbSet<categoria> categoria { get; set; }
        public DbSet<docente> docente { get; set; }
        public DbSet<estadomaterial> estadomaterial { get; set; }
        public DbSet<estadoprestamo> estadoprestamo { get; set; }
        public DbSet<material> material { get; set; }
        public DbSet<prestamo> prestamo { get; set; }
        public DbSet<prestamomaterial> prestamomaterial { get; set; }
        public DbSet<alumno> alumno { get; set; }
    }
}
