//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        public material()
        {
            this.prestamomaterial = new HashSet<prestamomaterial>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int CategoriaId { get; set; }
        public byte[] Imagen { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual ICollection<prestamomaterial> prestamomaterial { get; set; }
    }
}
